source 'https://rubygems.org'

gem 'sqlite3'
gem 'sinatra'
gem 'json'
gem 'data_mapper'
gem 'shotgun'
gem 'twitter'
gem 'rmagick'
gem 'premailer'
gem 'fog', '~>1.22.0'
gem 'mail'
gem 'dm-sqlite-adapter'