source 'https://rubygems.org'

gem 'sqlite3'
gem 'sinatra'
gem 'json'
gem 'data_mapper'
gem 'slim'
gem 'haml'
gem 'shotgun'
gem 'twitter'
gem 'omniauth-twitter'
gem 'pony'
gem 'rmagick'
gem 'premailer'